export const cars = [
  // Teslat (dealership_id: 1)
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model 3',
    year: '2021',
    license_plate: 'TES-001',
    seats: 5,
    latitude: 60.1695,
    longitude: 24.9354,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 2,
    brand: 'Tesla',
    model: 'Model Y',
    year: '2022',
    license_plate: 'TES-002',
    seats: 5,
    latitude: 60.2055,
    longitude: 24.6559,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 3,
    brand: 'Tesla',
    model: 'Model S',
    year: '2020',
    license_plate: 'TES-003',
    seats: 5,
    latitude: 60.25,
    longitude: 24.8,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 4,
    brand: 'Tesla',
    model: 'Model X',
    year: '2023',
    license_plate: 'TES-004',
    seats: 7,
    latitude: 60.2938,
    longitude: 25.0378,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 5,
    brand: 'Tesla',
    model: 'Model 3',
    year: '2021',
    license_plate: 'TES-005',
    seats: 5,
    latitude: 60.2354,
    longitude: 24.9458,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 6,
    brand: 'Tesla',
    model: 'Model Y',
    year: '2022',
    license_plate: 'TES-006',
    seats: 5,
    latitude: 60.2755,
    longitude: 24.8459,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 7,
    brand: 'Tesla',
    model: 'Model S',
    year: '2020',
    license_plate: 'TES-007',
    seats: 5,
    latitude: 60.192,
    longitude: 24.945,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 8,
    brand: 'Tesla',
    model: 'Model X',
    year: '2019',
    license_plate: 'TES-008',
    seats: 7,
    latitude: 60.1875,
    longitude: 24.8047,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 9,
    brand: 'Tesla',
    model: 'Model 3',
    year: '2023',
    license_plate: 'TES-009',
    seats: 5,
    latitude: 60.2521,
    longitude: 24.941,
    dealership_id: 1,
    reserved: false,
  },
  {
    id: 10,
    brand: 'Tesla',
    model: 'Model Y',
    year: '2023',
    license_plate: 'TES-010',
    seats: 5,
    latitude: 60.2145,
    longitude: 24.8211,
    dealership_id: 1,
    reserved: false,
  },

  // 20 muuta autoa, eri merkeiltä ja eri dealership_id
  {
    id: 11,
    brand: 'BMW',
    model: 'i3',
    year: '2020',
    license_plate: 'BMW-001',
    seats: 4,
    latitude: 60.186,
    longitude: 24.951,
    dealership_id: 2,
    reserved: false,
  },
  {
    id: 12,
    brand: 'Volkswagen',
    model: 'ID.4',
    year: '2022',
    license_plate: 'VW-001',
    seats: 5,
    latitude: 60.22,
    longitude: 24.88,
    dealership_id: 2,
    reserved: false,
  },
  {
    id: 13,
    brand: 'Kia',
    model: 'EV6',
    year: '2021',
    license_plate: 'KIA-001',
    seats: 5,
    latitude: 60.253,
    longitude: 24.905,
    dealership_id: 3,
    reserved: false,
  },
  {
    id: 14,
    brand: 'Nissan',
    model: 'Leaf',
    year: '2022',
    license_plate: 'NIS-001',
    seats: 5,
    latitude: 60.1925,
    longitude: 24.94,
    dealership_id: 3,
    reserved: false,
  },
  {
    id: 15,
    brand: 'Hyundai',
    model: 'Ioniq 5',
    year: '2023',
    license_plate: 'HYU-001',
    seats: 5,
    latitude: 60.295,
    longitude: 25.06,
    dealership_id: 4,
    reserved: false,
  },
  {
    id: 16,
    brand: 'Mercedes-Benz',
    model: 'EQV',
    year: '2022',
    license_plate: 'MER-001',
    seats: 7,
    latitude: 60.271,
    longitude: 24.84,
    dealership_id: 4,
    reserved: false,
  },
  {
    id: 17,
    brand: 'Peugeot',
    model: 'e-traveller',
    year: '2022',
    license_plate: 'PEU-001',
    seats: 8,
    latitude: 60.248,
    longitude: 24.845,
    dealership_id: 5,
    reserved: false,
  },
  {
    id: 18,
    brand: 'Renault',
    model: 'ZOE',
    year: '2021',
    license_plate: 'REN-001',
    seats: 5,
    latitude: 60.193,
    longitude: 24.949,
    dealership_id: 5,
    reserved: false,
  },
  {
    id: 19,
    brand: 'Fiat',
    model: '500e',
    year: '2023',
    license_plate: 'FIA-001',
    seats: 4,
    latitude: 60.165,
    longitude: 24.945,
    dealership_id: 5,
    reserved: false,
  },
  {
    id: 20,
    brand: 'Opel',
    model: 'Corsa-e',
    year: '2022',
    license_plate: 'OPE-001',
    seats: 5,
    latitude: 60.175,
    longitude: 24.961,
    dealership_id: 6,
    reserved: false,
  },
  {
    id: 21,
    brand: 'Skoda',
    model: 'Enyaq',
    year: '2022',
    license_plate: 'SKO-001',
    seats: 5,
    latitude: 60.225,
    longitude: 24.93,
    dealership_id: 2,
    reserved: false,
  },
  {
    id: 22,
    brand: 'Mini',
    model: 'Electric',
    year: '2021',
    license_plate: 'MIN-001',
    seats: 4,
    latitude: 60.205,
    longitude: 24.901,
    dealership_id: 3,
    reserved: false,
  },
  {
    id: 23,
    brand: 'Polestar',
    model: '2',
    year: '2022',
    license_plate: 'POL-001',
    seats: 5,
    latitude: 60.218,
    longitude: 24.981,
    dealership_id: 4,
    reserved: false,
  },
  {
    id: 24,
    brand: 'Mazda',
    model: 'MX-30',
    year: '2022',
    license_plate: 'MAZ-001',
    seats: 5,
    latitude: 60.275,
    longitude: 24.803,
    dealership_id: 5,
    reserved: false,
  },
  {
    id: 25,
    brand: 'Citroën',
    model: 'ë-C4',
    year: '2022',
    license_plate: 'CIT-001',
    seats: 5,
    latitude: 60.27,
    longitude: 24.915,
    dealership_id: 6,
    reserved: false,
  },
  {
    id: 26,
    brand: 'BYD',
    model: 'Atto 3',
    year: '2023',
    license_plate: 'BYD-001',
    seats: 5,
    latitude: 60.19,
    longitude: 24.936,
    dealership_id: 2,
    reserved: false,
  },
  {
    id: 27,
    brand: 'Volvo',
    model: 'XC40 Recharge',
    year: '2022',
    license_plate: 'VOL-001',
    seats: 5,
    latitude: 60.237,
    longitude: 24.951,
    dealership_id: 3,
    reserved: false,
  },
  {
    id: 28,
    brand: 'Ford',
    model: 'Mustang Mach-E',
    year: '2021',
    license_plate: 'FOR-001',
    seats: 5,
    latitude: 60.189,
    longitude: 24.926,
    dealership_id: 4,
    reserved: false,
  },
  {
    id: 29,
    brand: 'Honda',
    model: 'e',
    year: '2021',
    license_plate: 'HON-001',
    seats: 4,
    latitude: 60.226,
    longitude: 24.87,
    dealership_id: 5,
    reserved: false,
  },
  {
    id: 30,
    brand: 'Toyota',
    model: 'bZ4X',
    year: '2023',
    license_plate: 'TOY-001',
    seats: 5,
    latitude: 60.258,
    longitude: 24.943,
    dealership_id: 6,
    reserved: false,
  },
];
